"""Intermediate-orbits helper toolkit for PolySpace coursework."""

from .Constants import J2_EARTH, MU_EARTH_KM3_S2, OMEGA_EARTH_RAD_S, R_EARTH_KM
from .OrbitalElements import (
    ClassicalOrbitalElements,
    StateVector,
    coe_to_rv,
    mean_motion_rad_s,
    orbital_period_s,
    rv_to_coe,
)
from .OrbitalFrames import (
    dcm_from_axes,
    ecef_to_eci,
    eci_to_ecef,
    eci_to_lvlh,
    eci_to_lvlh_dcm,
    eci_to_orbital_plane,
    eci_to_perifocal_dcm,
    lvlh_to_eci,
    perifocal_to_eci_dcm,
    relative_state_eci_to_lvlh,
    rot1,
    rot2,
    rot3,
    teme_to_ecef,
)
from .Propagators import (
    PropagationResult,
    j2_acceleration,
    propagate_custom,
    propagate_j2,
    propagate_two_body,
    propagate_universal_anomaly,
    universal_anomaly_state,
    two_body_acceleration,
)
from .TLETools import TLERecord, parse_tle_file
from .CesiumOrbit import CesiumScene, times_from_seconds, trajectory_packet

__all__ = [
    "MU_EARTH_KM3_S2",
    "R_EARTH_KM",
    "J2_EARTH",
    "OMEGA_EARTH_RAD_S",
    "ClassicalOrbitalElements",
    "StateVector",
    "coe_to_rv",
    "rv_to_coe",
    "mean_motion_rad_s",
    "orbital_period_s",
    "rot1",
    "rot2",
    "rot3",
    "dcm_from_axes",
    "eci_to_lvlh_dcm",
    "eci_to_lvlh",
    "lvlh_to_eci",
    "relative_state_eci_to_lvlh",
    "eci_to_perifocal_dcm",
    "perifocal_to_eci_dcm",
    "eci_to_orbital_plane",
    "eci_to_ecef",
    "ecef_to_eci",
    "teme_to_ecef",
    "PropagationResult",
    "two_body_acceleration",
    "j2_acceleration",
    "propagate_custom",
    "propagate_two_body",
    "propagate_universal_anomaly",
    "universal_anomaly_state",
    "propagate_j2",
    "TLERecord",
    "parse_tle_file",
    "CesiumScene",
    "trajectory_packet",
    "times_from_seconds",
]
